FROM python:3.10

WORKDIR /code

COPY ./requirements.txt /code/requirements.txt

RUN pip install --upgrade pip setuptools wheel

RUN pip install torch==2.7.0 torchvision==0.22.0 torchaudio==2.7.0 --index-url https://download.pytorch.org/whl/cpu

RUN pip install -r /code/requirements.txt

RUN python -c "import nltk;from sentence_transformers import SentenceTransformer;SentenceTransformer('intfloat/multilingual-e5-small'); nltk.download('punkt_tab'); nltk.download('stopwords')"

COPY ./app /code/app

CMD [ "python", "app/main.py"]
